name: Zaffari Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm install

      - name: Gerar Prisma Client
        run: npx prisma generate

      - name: Rodar scraper do Zaffari
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run scrape:zaffari